function init(self)
	math.randomseed(os.time())
	msg.post("paddle", "attach_ball", { ball_id = go.get_id("ball") })
end

function update(self, dt)
	msg.post("@render:", "clear_color", { color = vmath.vector4(0.25, 0.25, 0.25, 1) })
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") and message.group == hash("ball") then
		msg.post(message.other_id, "stop")
		msg.post("paddle", "attach_ball", { ball_id = message.other_id })
	end
end
